### ISSUE TITLE
Can not convert type of `Nullable(UInt64)`

### ISSUE THREAD

**Issue by iwecon** [patrick-zippenfenig/ClickHouseNIO#6]
I got an error with:
`ClickHouseNIO/DataMessage.swift:95: Fatal error: Unknown type Nullable(UInt64)`

Any ideas for the problem?

**Comment by patrick-zippenfenig** [comment]
How does your CREATE TABLE statement looks like?

**Comment by iwecon** [comment]
thanks for the update.
and i found an another way.

```sql
select
ifNull(coin, 0) as `UserCoin`
from user;
```
